trigger:
- master

pool:
  name: Default

steps:
- script: echo Building gradle
  displayName: 'Run a one-line script'

- script: gradle build
  displayName: 'Build and Deployment'

- script: gradle run
  displayName: 'Running jar'